version: '3.8'

services:
  discord-bot:
    build: .
    container_name: music-contest-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_PATH=/app/data/suno_contests.db
      - BACKUP_DIR=/app/data/backups
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - bot-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: bot-redis
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  # redis-data:
